version: '3'

services:
    app:
        build: .
        restart: always
        env_file:
          - .env
        volumes:
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro